import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/NavBar";
import { VoerkaI18nNextjsProvider } from "@/languages/client";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VoerkaI18n Next.js Example",
  description: "Generated by create next app & VoerkaI18n",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} >
        <VoerkaI18nNextjsProvider fallback={<div>loading language...</div>}>
          <Navbar/>    
          {children} 
        </VoerkaI18nNextjsProvider>
      </body>
    </html>
  );
}
