export const bcp47 = {
  "en": [
      {"tag": "zh-CN", "name": "Chinese (Simplified)", "nativeName": "简体中文 (Simplified Chinese)", "primary": true},
      {"tag": "zh-TW", "name": "Chinese (Traditional - Taiwan)", "nativeName": "繁體中文 (Traditional Chinese - Taiwan)"},
      {"tag": "zh-HK", "name": "Chinese (Traditional - Hong Kong)", "nativeName": "繁體中文 (Traditional Chinese - Hong Kong)"},
      {"tag": "zh-MO", "name": "Chinese (Traditional - Macau)", "nativeName": "繁體中文 (Traditional Chinese - Macau)"},
      {"tag": "zh-SG", "name": "Chinese (Simplified - Singapore)", "nativeName": "简体中文 (Simplified Chinese - Singapore)"},      
      {"tag": "zh-CHS", "name": "Chinese (Simplified)", "nativeName": "简体中文 (Simplified Chinese)"},
      {"tag": "zh-CHT", "name": "Chinese (Traditional)", "nativeName": "繁體中文 (Traditional Chinese)"},
      {"tag": "en-US", "name": "English (United States)", "nativeName": "English (United States)", "primary": true},
      {"tag": "en-GB", "name": "English (United Kingdom)", "nativeName": "English (United Kingdom)"},
      {"tag": "en-CA", "name": "English (Canada)", "nativeName": "English (Canada)"},
      {"tag": "en-AU", "name": "English (Australia)", "nativeName": "English (Australia)"},
      {"tag": "en-IN", "name": "English (India)", "nativeName": "English (India)"},
      {"tag": "en-ZA", "name": "English (South Africa)", "nativeName": "English (South Africa)"},
      {"tag": "en-NZ", "name": "English (New Zealand)", "nativeName": "English (New Zealand)"},
      {"tag": "en-IE", "name": "English (Ireland)", "nativeName": "English (Ireland)"},
      {"tag": "en-PH", "name": "English (Philippines)", "nativeName": "English (Philippines)"},
      {"tag": "en-ZW", "name": "English (Zimbabwe)", "nativeName": "English (Zimbabwe)"},
      {"tag": "en-BZ", "name": "English (Belize)", "nativeName": "English (Belize)"},
      {"tag": "en-CB", "name": "English (Caribbean)", "nativeName": "English (Caribbean)"},
      {"tag": "en-JM", "name": "English (Jamaica)", "nativeName": "English (Jamaica)"},
      {"tag": "en-TT", "name": "English (Trinidad and Tobago)", "nativeName": "English (Trinidad and Tobago)"},
      {"tag": "hi-IN", "name": "Hindi (India)", "nativeName": "हिन्दी (Hindi)"},
      {"tag": "es-ES", "name": "Spanish (Spain)", "nativeName": "Español (España)", "primary": true},
      {"tag": "es-MX", "name": "Spanish (Mexico)", "nativeName": "Español (México)"},
      {"tag": "es-AR", "name": "Spanish (Argentina)", "nativeName": "Español (Argentina)"},
      {"tag": "es-CO", "name": "Spanish (Colombia)", "nativeName": "Español (Colombia)"},
      {"tag": "es-PE", "name": "Spanish (Peru)", "nativeName": "Español (Perú)"},
      {"tag": "es-VE", "name": "Spanish (Venezuela)", "nativeName": "Español (Venezuela)"},
      {"tag": "es-CL", "name": "Spanish (Chile)", "nativeName": "Español (Chile)"},
      {"tag": "es-EC", "name": "Spanish (Ecuador)", "nativeName": "Español (Ecuador)"},
      {"tag": "es-GT", "name": "Spanish (Guatemala)", "nativeName": "Español (Guatemala)"},
      {"tag": "es-CU", "name": "Spanish (Cuba)", "nativeName": "Español (Cuba)"},
      {"tag": "es-BO", "name": "Spanish (Bolivia)", "nativeName": "Español (Bolivia)"},
      {"tag": "es-DO", "name": "Spanish (Dominican Republic)", "nativeName": "Español (República Dominicana)"},
      {"tag": "es-HN", "name": "Spanish (Honduras)", "nativeName": "Español (Honduras)"},
      {"tag": "es-PY", "name": "Spanish (Paraguay)", "nativeName": "Español (Paraguay)"},
      {"tag": "es-SV", "name": "Spanish (El Salvador)", "nativeName": "Español (El Salvador)"},
      {"tag": "es-NI", "name": "Spanish (Nicaragua)", "nativeName": "Español (Nicaragua)"},
      {"tag": "es-PR", "name": "Spanish (Puerto Rico)", "nativeName": "Español (Puerto Rico)"},
      {"tag": "es-UY", "name": "Spanish (Uruguay)", "nativeName": "Español (Uruguay)"},
      {"tag": "es-PA", "name": "Spanish (Panama)", "nativeName": "Español (Panamá)"},
      {"tag": "es-CR", "name": "Spanish (Costa Rica)", "nativeName": "Español (Costa Rica)"},
      {"tag": "ar-EG", "name": "Arabic (Egypt)", "nativeName": "العربية (مصر)", "primary": true},
      {"tag": "ar-SA", "name": "Arabic (Saudi Arabia)", "nativeName": "العربية (السعودية)"},
      {"tag": "ar-DZ", "name": "Arabic (Algeria)", "nativeName": "العربية (الجزائر)"},
      {"tag": "ar-MA", "name": "Arabic (Morocco)", "nativeName": "العربية (المغرب)"},
      {"tag": "ar-IQ", "name": "Arabic (Iraq)", "nativeName": "العربية (العراق)"},
      {"tag": "ar-SD", "name": "Arabic (Sudan)", "nativeName": "العربية (السودان)"},
      {"tag": "ar-YE", "name": "Arabic (Yemen)", "nativeName": "العربية (اليمن)"},
      {"tag": "ar-SY", "name": "Arabic (Syria)", "nativeName": "العربية (سوريا)"},
      {"tag": "ar-TN", "name": "Arabic (Tunisia)", "nativeName": "العربية (تونس)"},
      {"tag": "ar-LY", "name": "Arabic (Libya)", "nativeName": "العربية (ليبيا)"},
      {"tag": "ar-JO", "name": "Arabic (Jordan)", "nativeName": "العربية (الأردن)"},
      {"tag": "ar-LB", "name": "Arabic (Lebanon)", "nativeName": "العربية (لبنان)"},
      {"tag": "ar-KW", "name": "Arabic (Kuwait)", "nativeName": "العربية (الكويت)"},
      {"tag": "ar-AE", "name": "Arabic (United Arab Emirates)", "nativeName": "العربية (الإمارات)"},
      {"tag": "ar-BH", "name": "Arabic (Bahrain)", "nativeName": "العربية (البحرين)"},
      {"tag": "ar-QA", "name": "Arabic (Qatar)", "nativeName": "العربية (قطر)"},
      {"tag": "ar-OM", "name": "Arabic (Oman)", "nativeName": "العربية (عمان)"},
      {"tag": "pt-BR", "name": "Portuguese (Brazil)", "nativeName": "Português (Brasil)"},
      {"tag": "pt-PT", "name": "Portuguese (Portugal)", "nativeName": "Português (Portugal)", "primary": true},
      {"tag": "ru-RU", "name": "Russian (Russia)", "nativeName": "Русский (Россия)", "primary": true},
      {"tag": "ja-JP", "name": "Japanese (Japan)", "nativeName": "日本語 (日本)"},
      {"tag": "de-DE", "name": "German (Germany)", "nativeName": "Deutsch (Deutschland)"},
      {"tag": "de-AT", "name": "German (Austria)", "nativeName": "Deutsch (Österreich)"},
      {"tag": "de-CH", "name": "German (Switzerland)", "nativeName": "Deutsch (Schweiz)"},
      {"tag": "fr-FR", "name": "French (France)", "nativeName": "Français (France)", "primary": true},
      {"tag": "fr-CA", "name": "French (Canada)", "nativeName": "Français (Canada)"},
      {"tag": "fr-BE", "name": "French (Belgium)", "nativeName": "Français (Belgique)"},
      {"tag": "fr-CH", "name": "French (Switzerland)", "nativeName": "Français (Suisse)"},
      {"tag": "fr-LU", "name": "French (Luxembourg)", "nativeName": "Français (Luxembourg)"},
      {"tag": "fr-MC", "name": "French (Monaco)", "nativeName": "Français (Monaco)"},
      {"tag": "ko-KR", "name": "Korean (South Korea)", "nativeName": "한국어 (대한민국)"},
      {"tag": "it-IT", "name": "Italian (Italy)", "nativeName": "Italiano (Italia)"},
      {"tag": "it-CH", "name": "Italian (Switzerland)", "nativeName": "Italiano (Svizzera)"},
      {"tag": "nl-NL", "name": "Dutch (Netherlands)", "nativeName": "Nederlands (Nederland)"},
      {"tag": "nl-BE", "name": "Dutch (Belgium)", "nativeName": "Nederlands (België)"},
      {"tag": "pl-PL", "name": "Polish (Poland)", "nativeName": "Polski (Polska)"},
      {"tag": "vi-VN", "name": "Vietnamese (Vietnam)", "nativeName": "Tiếng Việt (Việt Nam)"},
      {"tag": "tr-TR", "name": "Turkish (Turkey)", "nativeName": "Türkçe (Türkiye)"},
      {"tag": "th-TH", "name": "Thai (Thailand)", "nativeName": "ไทย (ประเทศไทย)"},
      {"tag": "el-GR", "name": "Greek (Greece)", "nativeName": "Ελληνικά (Ελλάδα)"},
      {"tag": "cs-CZ", "name": "Czech (Czech Republic)", "nativeName": "Čeština (Česká republika)"},
      {"tag": "sv-SE", "name": "Swedish (Sweden)", "nativeName": "Svenska (Sverige)"},
      {"tag": "sv-FI", "name": "Swedish (Finland)", "nativeName": "Svenska (Finland)"},
      {"tag": "hu-HU", "name": "Hungarian (Hungary)", "nativeName": "Magyar (Magyarország)"},
      {"tag": "fi-FI", "name": "Finnish (Finland)", "nativeName": "Suomi (Suomi)"},
      {"tag": "da-DK", "name": "Danish (Denmark)", "nativeName": "Dansk (Danmark)"},
      {"tag": "nb-NO", "name": "Norwegian Bokmål (Norway)", "nativeName": "Norsk Bokmål (Norge)"},
      {"tag": "nn-NO", "name": "Norwegian Nynorsk (Norway)", "nativeName": "Norsk Nynorsk (Norge)"},
      {"tag": "he-IL", "name": "Hebrew (Israel)", "nativeName": "עברית (ישראל)"},
      {"tag": "id-ID", "name": "Indonesian (Indonesia)", "nativeName": "Bahasa Indonesia (Indonesia)"},
      {"tag": "ms-MY", "name": "Malay (Malaysia)", "nativeName": "Bahasa Melayu (Malaysia)"},
      {"tag": "ms-BN", "name": "Malay (Brunei)", "nativeName": "Bahasa Melayu (Brunei)"},
      {"tag": "ro-RO", "name": "Romanian (Romania)", "nativeName": "Română (România)"},
      {"tag": "bg-BG", "name": "Bulgarian (Bulgaria)", "nativeName": "Български (България)"},
      {"tag": "uk-UA", "name": "Ukrainian (Ukraine)", "nativeName": "Українська (Україна)"},
      {"tag": "sk-SK", "name": "Slovak (Slovakia)", "nativeName": "Slovenčina (Slovensko)"},
      {"tag": "sl-SI", "name": "Slovene (Slovenia)", "nativeName": "Slovenščina (Slovenija)"},
      {"tag": "hr-HR", "name": "Croatian (Croatia)", "nativeName": "Hrvatski (Hrvatska)"},
      {"tag": "ca-ES", "name": "Catalan (Catalonia)", "nativeName": "Català (Catalunya)"},
      {"tag": "lt-LT", "name": "Lithuanian (Lithuania)", "nativeName": "Lietuvių (Lietuva)"},
      {"tag": "lv-LV", "name": "Latvian (Latvia)", "nativeName": "Latviešu (Latvija)"},
      {"tag": "et-EE", "name": "Estonian (Estonia)", "nativeName": "Eesti (Eesti)"},
      {"tag": "sq-AL", "name": "Albanian (Albania)", "nativeName": "Shqip (Shqipëri)"},
      {"tag": "mk-MK", "name": "Macedonian (North Macedonia)", "nativeName": "Македонски (Македонија)"},
      {"tag": "be-BY", "name": "Belarusian (Belarus)", "nativeName": "Беларуская (Беларусь)"},
      {"tag": "is-IS", "name": "Icelandic (Iceland)", "nativeName": "Íslenska (Ísland)"},
      {"tag": "gl-ES", "name": "Galician (Galicia)", "nativeName": "Galego (Galicia)"},
      {"tag": "eu-ES", "name": "Basque (Basque Country)", "nativeName": "Euskara (Euskal Herria)"},
      {"tag": "af-ZA", "name": "Afrikaans (South Africa)", "nativeName": "Afrikaans (Suid-Afrika)"},
      {"tag": "sw-KE", "name": "Swahili (Kenya)", "nativeName": "Kiswahili (Kenya)"},
      {"tag": "ta-IN", "name": "Tamil (India)", "nativeName": "தமிழ் (இந்தியா)"},
      {"tag": "te-IN", "name": "Telugu (India)", "nativeName": "తెలుగు (భారతదేశం)"},
      {"tag": "kn-IN", "name": "Kannada (India)", "nativeName": "ಕನ್ನಡ (ಭಾರತ)"},
      {"tag": "mr-IN", "name": "Marathi (India)", "nativeName": "मराठी (भारत)"},
      {"tag": "gu-IN", "name": "Gujarati (India)", "nativeName": "ગુજરાતી (ભારત)"},
      {"tag": "pa-IN", "name": "Punjabi (India)", "nativeName": "ਪੰਜਾਬੀ (ਭਾਰਤ)"},
      {"tag": "kok-IN", "name": "Konkani (India)", "nativeName": "कोंकणी (भारत)"},
      {"tag": "sa-IN", "name": "Sanskrit (India)", "nativeName": "संस्कृत (भारत)"},
      {"tag": "ur-PK", "name": "Urdu (Pakistan)", "nativeName": "اردو (پاکستان)"},
      {"tag": "fa-IR", "name": "Persian (Iran)", "nativeName": "فارسی (ایران)"},
      {"tag": "syr-SY", "name": "Syriac (Syria)", "nativeName": "ܣܘܪܝܝܐ (ܣܘܪܝܐ)"},
      {"tag": "div-MV", "name": "Dhivehi (Maldives)", "nativeName": "ދިވެހި (މޯލްޑިވްސް)"},
      {"tag": "ka-GE", "name": "Georgian (Georgia)", "nativeName": "ქართული (საქართველო)"},      
  ],
  "zh": [
      {"tag": "zh-CN", "name": "简体中文", "nativeName": "简体中文 (Simplified Chinese)", "primary": true},
      {"tag": "zh-TW", "name": "繁体中文（台湾）", "nativeName": "繁體中文 (Traditional Chinese - Taiwan)"},
      {"tag": "zh-HK", "name": "繁体中文（香港）", "nativeName": "繁體中文 (Traditional Chinese - Hong Kong)"},
      {"tag": "zh-SG", "name": "简体中文（新加坡）", "nativeName": "简体中文 (Simplified Chinese - Singapore)"},
      {"tag": "zh-MO", "name": "繁体中文（澳门）", "nativeName": "繁體中文 (Traditional Chinese - Macau)"},
      {"tag": "zh-CHS", "name": "简体中文", "nativeName": "简体中文 (Simplified Chinese)"},
      {"tag": "zh-CHT", "name": "繁体中文", "nativeName": "繁體中文 (Traditional Chinese)"},
      {"tag": "en-US", "name": "英语（美国）", "nativeName": "English (United States)", "primary": true},
      {"tag": "en-GB", "name": "英语（英国）", "nativeName": "English (United Kingdom)"},
      {"tag": "en-IN", "name": "英语（印度）", "nativeName": "English (India)"},
      {"tag": "en-CA", "name": "英语（加拿大）", "nativeName": "English (Canada)"},
      {"tag": "en-AU", "name": "英语（澳大利亚）", "nativeName": "English (Australia)"},
      {"tag": "en-ZA", "name": "英语（南非）", "nativeName": "English (South Africa)"},
      {"tag": "en-NZ", "name": "英语（新西兰）", "nativeName": "English (New Zealand)"},
      {"tag": "en-IE", "name": "英语（爱尔兰）", "nativeName": "English (Ireland)"},
      {"tag": "en-PH", "name": "英语（菲律宾）", "nativeName": "English (Philippines)"},
      {"tag": "en-ZW", "name": "英语（津巴布韦）", "nativeName": "English (Zimbabwe)"},
      {"tag": "en-BZ", "name": "英语（伯利兹）", "nativeName": "English (Belize)"},
      {"tag": "en-CB", "name": "英语（加勒比地区）", "nativeName": "English (Caribbean)"},
      {"tag": "en-JM", "name": "英语（牙买加）", "nativeName": "English (Jamaica)"},
      {"tag": "en-TT", "name": "英语（特立尼达和多巴哥）", "nativeName": "English (Trinidad and Tobago)"},
      {"tag": "hi-IN", "name": "印地语", "nativeName": "हिन्दी (Hindi)"},
      {"tag": "es-ES", "name": "西班牙语（西班牙）", "nativeName": "Español (España)", "primary": true},
      {"tag": "es-MX", "name": "西班牙语（墨西哥）", "nativeName": "Español (México)"},
      {"tag": "es-AR", "name": "西班牙语（阿根廷）", "nativeName": "Español (Argentina)"},
      {"tag": "es-CO", "name": "西班牙语（哥伦比亚）", "nativeName": "Español (Colombia)"},
      {"tag": "es-PE", "name": "西班牙语（秘鲁）", "nativeName": "Español (Perú)"},
      {"tag": "es-VE", "name": "西班牙语（委内瑞拉）", "nativeName": "Español (Venezuela)"},
      {"tag": "es-CL", "name": "西班牙语（智利）", "nativeName": "Español (Chile)"},
      {"tag": "es-EC", "name": "西班牙语（厄瓜多尔）", "nativeName": "Español (Ecuador)"},
      {"tag": "es-GT", "name": "西班牙语（危地马拉）", "nativeName": "Español (Guatemala)"},
      {"tag": "es-CU", "name": "西班牙语（古巴）", "nativeName": "Español (Cuba)"},
      {"tag": "es-BO", "name": "西班牙语（玻利维亚）", "nativeName": "Español (Bolivia)"},
      {"tag": "es-DO", "name": "西班牙语（多米尼加共和国）", "nativeName": "Español (República Dominicana)"},
      {"tag": "es-HN", "name": "西班牙语（洪都拉斯）", "nativeName": "Español (Honduras)"},
      {"tag": "es-PY", "name": "西班牙语（巴拉圭）", "nativeName": "Español (Paraguay)"},
      {"tag": "es-SV", "name": "西班牙语（萨尔瓦多）", "nativeName": "Español (El Salvador)"},
      {"tag": "es-NI", "name": "西班牙语（尼加拉瓜）", "nativeName": "Español (Nicaragua)"},
      {"tag": "es-PR", "name": "西班牙语（波多黎各）", "nativeName": "Español (Puerto Rico)"},
      {"tag": "es-UY", "name": "西班牙语（乌拉圭）", "nativeName": "Español (Uruguay)"},
      {"tag": "es-PA", "name": "西班牙语（巴拿马）", "nativeName": "Español (Panamá)"},
      {"tag": "es-CR", "name": "西班牙语（哥斯达黎加）", "nativeName": "Español (Costa Rica)"},
      {"tag": "ar-EG", "name": "阿拉伯语（埃及）", "nativeName": "العربية (مصر)", "primary": true},
      {"tag": "ar-SA", "name": "阿拉伯语（沙特阿拉伯）", "nativeName": "العربية (السعودية)"},
      {"tag": "ar-DZ", "name": "阿拉伯语（阿尔及利亚）", "nativeName": "العربية (الجزائر)"},
      {"tag": "ar-MA", "name": "阿拉伯语（摩洛哥）", "nativeName": "العربية (المغرب)"},
      {"tag": "ar-IQ", "name": "阿拉伯语（伊拉克）", "nativeName": "العربية (العراق)"},
      {"tag": "ar-SD", "name": "阿拉伯语（苏丹）", "nativeName": "العربية (السودان)"},
      {"tag": "ar-YE", "name": "阿拉伯语（也门）", "nativeName": "العربية (اليمن)"},
      {"tag": "ar-SY", "name": "阿拉伯语（叙利亚）", "nativeName": "العربية (سوريا)"},
      {"tag": "ar-TN", "name": "阿拉伯语（突尼斯）", "nativeName": "العربية (تونس)"},
      {"tag": "ar-LY", "name": "阿拉伯语（利比亚）", "nativeName": "العربية (ليبيا)"},
      {"tag": "ar-JO", "name": "阿拉伯语（约旦）", "nativeName": "العربية (الأردن)"},
      {"tag": "ar-LB", "name": "阿拉伯语（黎巴嫩）", "nativeName": "العربية (لبنان)"},
      {"tag": "ar-KW", "name": "阿拉伯语（科威特）", "nativeName": "العربية (الكويت)"},
      {"tag": "ar-AE", "name": "阿拉伯语（阿联酋）", "nativeName": "العربية (الإمارات)"},
      {"tag": "ar-BH", "name": "阿拉伯语（巴林）", "nativeName": "العربية (البحرين)"},
      {"tag": "ar-QA", "name": "阿拉伯语（卡塔尔）", "nativeName": "العربية (قطر)"},
      {"tag": "ar-OM", "name": "阿拉伯语（阿曼）", "nativeName": "العربية (عمان)"},
      {"tag": "pt-BR", "name": "葡萄牙语（巴西）", "nativeName": "Português (Brasil)"},
      {"tag": "pt-PT", "name": "葡萄牙语（葡萄牙）", "nativeName": "Português (Portugal)", "primary": true},
      {"tag": "ru-RU", "name": "俄语", "nativeName": "Русский (Россия)", "primary": true},
      {"tag": "ja-JP", "name": "日语", "nativeName": "日本語 (日本)"},
      {"tag": "de-DE", "name": "德语（德国）", "nativeName": "Deutsch (Deutschland)"},
      {"tag": "de-AT", "name": "德语（奥地利）", "nativeName": "Deutsch (Österreich)"},
      {"tag": "de-CH", "name": "德语（瑞士）", "nativeName": "Deutsch (Schweiz)"},
      {"tag": "fr-FR", "name": "法语（法国）", "nativeName": "Français (France)", "primary": true},
      {"tag": "fr-CA", "name": "法语（加拿大）", "nativeName": "Français (Canada)"},
      {"tag": "fr-BE", "name": "法语（比利时）", "nativeName": "Français (Belgique)"},
      {"tag": "fr-CH", "name": "法语（瑞士）", "nativeName": "Français (Suisse)"},
      {"tag": "fr-LU", "name": "法语（卢森堡）", "nativeName": "Français (Luxembourg)"},
      {"tag": "fr-MC", "name": "法语（摩纳哥）", "nativeName": "Français (Monaco)"},
      {"tag": "ko-KR", "name": "韩语", "nativeName": "한국어 (대한민국)"},
      {"tag": "it-IT", "name": "意大利语", "nativeName": "Italiano (Italia)"},
      {"tag": "it-CH", "name": "意大利语（瑞士）", "nativeName": "Italiano (Svizzera)"},
      {"tag": "nl-NL", "name": "荷兰语", "nativeName": "Nederlands (Nederland)"},
      {"tag": "nl-BE", "name": "荷兰语（比利时）", "nativeName": "Nederlands (België)"},
      {"tag": "pl-PL", "name": "波兰语", "nativeName": "Polski (Polska)"},
      {"tag": "vi-VN", "name": "越南语", "nativeName": "Tiếng Việt (Việt Nam)"},
      {"tag": "tr-TR", "name": "土耳其语", "nativeName": "Türkçe (Türkiye)"},
      {"tag": "th-TH", "name": "泰语", "nativeName": "ไทย (ประเทศไทย)"},
      {"tag": "el-GR", "name": "希腊语", "nativeName": "Ελληνικά (Ελλάδα)"},
      {"tag": "cs-CZ", "name": "捷克语", "nativeName": "Čeština (Česká republika)"},
      {"tag": "sv-SE", "name": "瑞典语", "nativeName": "Svenska (Sverige)"},
      {"tag": "sv-FI", "name": "瑞典语（芬兰）", "nativeName": "Svenska (Finland)"},
      {"tag": "hu-HU", "name": "匈牙利语", "nativeName": "Magyar (Magyarország)"},
      {"tag": "fi-FI", "name": "芬兰语", "nativeName": "Suomi (Suomi)"},
      {"tag": "da-DK", "name": "丹麦语", "nativeName": "Dansk (Danmark)"},
      {"tag": "nb-NO", "name": "挪威博克马尔语", "nativeName": "Norsk Bokmål (Norge)"},
      {"tag": "nn-NO", "name": "挪威尼诺斯克语", "nativeName": "Norsk Nynorsk (Norge)"},
      {"tag": "he-IL", "name": "希伯来语", "nativeName": "עברית (ישראל)"},
      {"tag": "id-ID", "name": "印度尼西亚语", "nativeName": "Bahasa Indonesia (Indonesia)"},
      {"tag": "ms-MY", "name": "马来语（马来西亚）", "nativeName": "Bahasa Melayu (Malaysia)"},
      {"tag": "ms-BN", "name": "马来语（文莱）", "nativeName": "Bahasa Melayu (Brunei)"},
      {"tag": "ro-RO", "name": "罗马尼亚语", "nativeName": "Română (România)"},
      {"tag": "bg-BG", "name": "保加利亚语", "nativeName": "Български (България)"},
      {"tag": "uk-UA", "name": "乌克兰语", "nativeName": "Українська (Україна)"},
      {"tag": "sk-SK", "name": "斯洛伐克语", "nativeName": "Slovenčina (Slovensko)"},
      {"tag": "sl-SI", "name": "斯洛文尼亚语", "nativeName": "Slovenščina (Slovenija)"},
      {"tag": "hr-HR", "name": "克罗地亚语", "nativeName": "Hrvatski (Hrvatska)"},
      {"tag": "ca-ES", "name": "加泰罗尼亚语", "nativeName": "Català (Catalunya)"},
      {"tag": "lt-LT", "name": "立陶宛语", "nativeName": "Lietuvių (Lietuva)"},
      {"tag": "lv-LV", "name": "拉脱维亚语", "nativeName": "Latviešu (Latvija)"},
      {"tag": "et-EE", "name": "爱沙尼亚语", "nativeName": "Eesti (Eesti)"},
      {"tag": "sq-AL", "name": "阿尔巴尼亚语", "nativeName": "Shqip (Shqipëri)"},
      {"tag": "mk-MK", "name": "马其顿语", "nativeName": "Македонски (Македонија)"},
      {"tag": "be-BY", "name": "白俄罗斯语", "nativeName": "Беларуская (Беларусь)"},
      {"tag": "is-IS", "name": "冰岛语", "nativeName": "Íslenska (Ísland)"},
      {"tag": "gl-ES", "name": "加利西亚语", "nativeName": "Galego (Galicia)"},
      {"tag": "eu-ES", "name": "巴斯克语", "nativeName": "Euskara (Euskal Herria)"},
      {"tag": "af-ZA", "name": "南非荷兰语", "nativeName": "Afrikaans (Suid-Afrika)"},
      {"tag": "sw-KE", "name": "斯瓦希里语", "nativeName": "Kiswahili (Kenya)"},
      {"tag": "ta-IN", "name": "泰米尔语", "nativeName": "தமிழ் (இந்தியா)"},
      {"tag": "te-IN", "name": "泰卢固语", "nativeName": "తెలుగు (భారతదేశం)"},
      {"tag": "kn-IN", "name": "卡纳达语", "nativeName": "ಕನ್ನಡ (ಭಾರತ)"},
      {"tag": "mr-IN", "name": "马拉地语", "nativeName": "मराठी (भारत)"},
      {"tag": "gu-IN", "name": "古吉拉特语", "nativeName": "ગુજરાતી (ભારત)"},
      {"tag": "pa-IN", "name": "旁遮普语", "nativeName": "ਪੰਜਾਬੀ (ਭਾਰਤ)"},
      {"tag": "kok-IN", "name": "孔卡尼语", "nativeName": "कोंकणी (भारत)"},
      {"tag": "sa-IN", "name": "梵语", "nativeName": "संस्कृत (भारत)"},
      {"tag": "ur-PK", "name": "乌尔都语", "nativeName": "اردو (پاکستان)"},
      {"tag": "fa-IR", "name": "波斯语", "nativeName": "فارسی (ایران)"},
      {"tag": "syr-SY", "name": "叙利亚语", "nativeName": "ܣܘܪܝܝܐ (ܣܘܪܝܐ)"},
      {"tag": "div-MV", "name": "迪维希语", "nativeName": "ދިވެހި (މޯލްޑިވްސް)"},
      {"tag": "ka-GE", "name": "格鲁吉亚语", "nativeName": "ქართული (საქართველო)"}
  ]
}

 
type BCP47LanguageTag = 
  // 简体中文 | 繁体中文(台湾) | 繁体中文(香港) | 繁体中文(澳门) | 简体中文(新加坡) | 简体中文 | 繁体中文 | 英语(美国) | 英语(英国) | 英语(加拿大)
  | "zh-CN" | "zh-TW" | "zh-HK" | "zh-MO" | "zh-SG" | "zh-CHS" | "zh-CHT" | "en-US" | "en-GB" | "en-CA"
  // 英语(澳大利亚) | 英语(印度) | 英语(南非) | 英语(新西兰) | 英语(爱尔兰) | 英语(菲律宾) | 英语(津巴布韦) | 英语(伯利兹) | 英语(加勒比) | 英语(牙买加)
  | "en-AU" | "en-IN" | "en-ZA" | "en-NZ" | "en-IE" | "en-PH" | "en-ZW" | "en-BZ" | "en-CB" | "en-JM"
  // 英语(特立尼达和多巴哥) | 印地语(印度) | 西班牙语(西班牙) | 西班牙语(墨西哥) | 西班牙语(阿根廷) | 西班牙语(哥伦比亚) | 西班牙语(秘鲁) | 西班牙语(委内瑞拉) | 西班牙语(智利) | 西班牙语(厄瓜多尔)
  | "en-TT" | "hi-IN" | "es-ES" | "es-MX" | "es-AR" | "es-CO" | "es-PE" | "es-VE" | "es-CL" | "es-EC"
  // 西班牙语(危地马拉) | 西班牙语(古巴) | 西班牙语(玻利维亚) | 西班牙语(多米尼加共和国) | 西班牙语(洪都拉斯) | 西班牙语(巴拉圭) | 西班牙语(萨尔瓦多) | 西班牙语(尼加拉瓜) | 西班牙语(波多黎各) | 西班牙语(乌拉圭)
  | "es-GT" | "es-CU" | "es-BO" | "es-DO" | "es-HN" | "es-PY" | "es-SV" | "es-NI" | "es-PR" | "es-UY"
  // 西班牙语(巴拿马) | 西班牙语(哥斯达黎加) | 阿拉伯语(埃及) | 阿拉伯语(沙特阿拉伯) | 阿拉伯语(阿尔及利亚) | 阿拉伯语(摩洛哥) | 阿拉伯语(伊拉克) | 阿拉伯语(苏丹) | 阿拉伯语(也门) | 阿拉伯语(叙利亚)
  | "es-PA" | "es-CR" | "ar-EG" | "ar-SA" | "ar-DZ" | "ar-MA" | "ar-IQ" | "ar-SD" | "ar-YE" | "ar-SY"
  // 阿拉伯语(突尼斯) | 阿拉伯语(利比亚) | 阿拉伯语(约旦) | 阿拉伯语(黎巴嫩) | 阿拉伯语(科威特) | 阿拉伯语(阿联酋) | 阿拉伯语(巴林) | 阿拉伯语(卡塔尔) | 阿拉伯语(阿曼) | 葡萄牙语(巴西)
  | "ar-TN" | "ar-LY" | "ar-JO" | "ar-LB" | "ar-KW" | "ar-AE" | "ar-BH" | "ar-QA" | "ar-OM" | "pt-BR"
  // 葡萄牙语(葡萄牙) | 俄语(俄罗斯) | 日语(日本) | 德语(德国) | 德语(奥地利) | 德语(瑞士) | 法语(法国) | 法语(加拿大) | 法语(比利时) | 法语(瑞士)
  | "pt-PT" | "ru-RU" | "ja-JP" | "de-DE" | "de-AT" | "de-CH" | "fr-FR" | "fr-CA" | "fr-BE" | "fr-CH"
  // 法语(卢森堡) | 法语(摩纳哥) | 韩语(韩国) | 意大利语(意大利) | 意大利语(瑞士) | 土耳其语 | 泰语 | 希腊语 | 捷克语 | 瑞典语
  | "fr-LU" | "fr-MC" | "ko-KR" | "it-IT" | "it-CH" | "tr-TR" | "th-TH" | "el-GR" | "cs-CZ" | "sv-SE"
  // 瑞典语(芬兰) | 匈牙利语 | 芬兰语 | 丹麦语 | 挪威博克马尔语 | 挪威尼诺斯克语 | 希伯来语 | 印度尼西亚语 | 马来语(马来西亚) | 马来语(文莱)
  | "sv-FI" | "hu-HU" | "fi-FI" | "da-DK" | "nb-NO" | "nn-NO" | "he-IL" | "id-ID" | "ms-MY" | "ms-BN"
  // 罗马尼亚语 | 保加利亚语 | 乌克兰语 | 斯洛伐克语 | 斯洛文尼亚语 | 克罗地亚语 | 加泰罗尼亚语 | 立陶宛语 | 拉脱维亚语 | 爱沙尼亚语
  | "ro-RO" | "bg-BG" | "uk-UA" | "sk-SK" | "sl-SI" | "hr-HR" | "ca-ES" | "lt-LT" | "lv-LV" | "et-EE"
  // 阿尔巴尼亚语 | 马其顿语 | 白俄罗斯语 | 冰岛语 | 加利西亚语 | 巴斯克语 | 南非荷兰语 | 斯瓦希里语 | 泰米尔语 | 泰卢固语
  | "sq-AL" | "mk-MK" | "be-BY" | "is-IS" | "gl-ES" | "eu-ES" | "af-ZA" | "sw-KE" | "ta-IN" | "te-IN"
  // 卡纳达语 | 马拉地语 | 古吉拉特语 | 旁遮普语 | 孔卡尼语 | 梵语 | 乌尔都语 | 波斯语 | 叙利亚语 | 迪维希语
  | "kn-IN" | "mr-IN" | "gu-IN" | "pa-IN" | "kok-IN" | "sa-IN" | "ur-PK" | "fa-IR" | "syr-SY" | "div-MV"
  // 格鲁吉亚语
  | "ka-GE";


