export default {
    en:[
        {code: 'en', name: 'English', nativeName: 'English'},
        {code: 'zh', name: 'Chinese', nativeName: '中文'},
        {code: 'hi', name: 'Hindi', nativeName: 'हिन्दी'},
        {code: 'es', name: 'Spanish', nativeName: 'Español'},
        {code: 'fr', name: 'French', nativeName: 'Français'},
        {code: 'ar', name: 'Arabic', nativeName: 'العربية'},
        {code: 'bn', name: 'Bengali', nativeName: 'বাংলা'},
        {code: 'ru', name: 'Russian', nativeName: 'Русский'},
        {code: 'pt', name: 'Portuguese', nativeName: 'Português'},
        {code: 'ur', name: 'Urdu', nativeName: 'اردو'},
        {code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia'},
        {code: 'de', name: 'German', nativeName: 'Deutsch'},
        {code: 'ja', name: 'Japanese', nativeName: '日本語'},
        {code: 'sw', name: 'Swahili', nativeName: 'Kiswahili'},
        {code: 'mr', name: 'Marathi', nativeName: 'मराठी'},
        {code: 'te', name: 'Telugu', nativeName: 'తెలుగు'},
        {code: 'tr', name: 'Turkish', nativeName: 'Türkçe'},
        {code: 'ta', name: 'Tamil', nativeName: 'தமிழ்'},
        {code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt'},
        {code: 'ko', name: 'Korean', nativeName: '한국어'},
        {code: 'it', name: 'Italian', nativeName: 'Italiano'},
        {code: 'th', name: 'Thai', nativeName: 'ไทย'},
        {code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી'},
        {code: 'pl', name: 'Polish', nativeName: 'Polski'},
        {code: 'uk', name: 'Ukrainian', nativeName: 'Українська'},
        {code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം'},
        {code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ'},
        {code: 'or', name: 'Oriya', nativeName: 'ଓଡ଼ିଆ'},
        {code: 'my', name: 'Burmese', nativeName: 'ဗမာစာ'},
        {code: 'pa', name: 'Panjabi', nativeName: 'ਪੰਜਾਬੀ'},
        {code: 'fa', name: 'Persian', nativeName: 'فارسی'},
        {code: 'nl', name: 'Dutch', nativeName: 'Nederlands'},
        {code: 'fil', name: 'Filipino', nativeName: 'Wikang Filipino'},
        {code: 'xh', name: 'Xhosa', nativeName: 'isiXhosa'},
        {code: 'zu', name: 'Zulu', nativeName: 'isiZulu'},
        {code: 'ro', name: 'Romanian', nativeName: 'Română'},
        {code: 'el', name: 'Greek', nativeName: 'Ελληνικά'},
        {code: 'cs', name: 'Czech', nativeName: 'čeština'},
        {code: 'sv', name: 'Swedish', nativeName: 'Svenska'},
        {code: 'hu', name: 'Hungarian', nativeName: 'magyar'},
        {code: 'fi', name: 'Finnish', nativeName: 'suomi'},
        {code: 'da', name: 'Danish', nativeName: 'Dansk'},
        {code: 'he', name: 'Hebrew', nativeName: 'עברית'},
        {code: 'no', name: 'Norwegian', nativeName: 'Norsk'},
        {code: 'sk', name: 'Slovak', nativeName: 'slovenčina'},
        {code: 'sl', name: 'Slovenian', nativeName: 'slovenščina'},
        {code: 'hr', name: 'Croatian', nativeName: 'Hrvatski'},
        {code: 'bg', name: 'Bulgarian', nativeName: 'български език'},
        {code: 'lt', name: 'Lithuanian', nativeName: 'lietuvių kalba'},
        {code: 'lv', name: 'Latvian', nativeName: 'latviešu valoda'},
        {code: 'et', name: 'Estonian', nativeName: 'eesti'},
        {code: 'ga', name: 'Irish', nativeName: 'Gaeilge'},
        {code: 'mt', name: 'Maltese', nativeName: 'Malti'},
        {code: 'cy', name: 'Welsh', nativeName: 'Cymraeg'},
        {code: 'gd', name: 'Scottish Gaelic', nativeName: 'Gàidhlig'},
        {code: 'is', name: 'Icelandic', nativeName: 'Íslenska'},
        {code: 'sq', name: 'Albanian', nativeName: 'Shqip'},
        {code: 'mk', name: 'Macedonian', nativeName: 'македонски јазик'},
        {code: 'bs', name: 'Bosnian', nativeName: 'bosanski jezik'},
        {code: 'sr', name: 'Serbian', nativeName: 'српски језик'},
        {code: 'ca', name: 'Catalan', nativeName: 'Català'},
        {code: 'eu', name: 'Basque', nativeName: 'euskara'},
        {code: 'gl', name: 'Galician', nativeName: 'galego'},
        {code: 'oc', name: 'Occitan', nativeName: 'occitan'},
        {code: 'ast', name: 'Asturian', nativeName: 'Asturianu'},
        {code: 'an', name: 'Aragonese', nativeName: 'aragonés'},
        {code: 'sc', name: 'Sardinian', nativeName: 'sardu'},
        {code: 'rm', name: 'Romansh', nativeName: 'rumantsch grischun'},
        {code: 'fur', name: 'Friulian', nativeName: 'Furlan'},
        {code: 'lad', name: 'Ladino', nativeName: 'Ladino'},
        {code: 'wa', name: 'Walloon', nativeName: 'walon'},
        {code: 'br', name: 'Breton', nativeName: 'brezhoneg'},
        {code: 'co', name: 'Corsican', nativeName: 'corsu'},
        {code: 'gv', name: 'Manx', nativeName: 'Gaelg'},
        {code: 'kw', name: 'Cornish', nativeName: 'Kernewek'},
        {code: 'fy', name: 'Western Frisian', nativeName: 'Frysk'},
        {code: 'li', name: 'Limburgish', nativeName: 'Limburgs'},
        {code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans'},
        {code: 'st', name: 'Southern Sotho', nativeName: 'Sesotho'},
        {code: 'tn', name: 'Tswana', nativeName: 'Setswana'},
        {code: 'ts', name: 'Tsonga', nativeName: 'Xitsonga'},
        {code: 'ss', name: 'Swati', nativeName: 'SiSwati'},
        {code: 've', name: 'Venda', nativeName: 'Tshivenḓa'},
        {code: 'nr', name: 'Southern Ndebele', nativeName: 'isiNdebele'},
        {code: 'xh', name: 'Xhosa', nativeName: 'isiXhosa'},
        {code: 'zu', name: 'Zulu', nativeName: 'isiZulu'},
        {code: 'sn', name: 'Shona', nativeName: 'chiShona'},
        {code: 'ny', name: 'Chichewa', nativeName: 'chiCheŵa'},
        {code: 'mg', name: 'Malagasy', nativeName: 'fiteny malagasy'},
        {code: 'rw', name: 'Kinyarwanda', nativeName: 'Ikinyarwanda'},
        {code: 'rn', name: 'Kirundi', nativeName: 'Ikirundi'},
        {code: 'sg', name: 'Sango', nativeName: 'yângâ tî sängö'},
        {code: 'lg', name: 'Ganda', nativeName: 'Luganda'},
        {code: 'ln', name: 'Lingala', nativeName: 'Lingála'},
        {code: 'sw', name: 'Swahili', nativeName: 'Kiswahili'},
        {code: 'so', name: 'Somali', nativeName: 'Soomaaliga'},
        {code: 'om', name: 'Oromo', nativeName: 'Afaan Oromoo'},
        {code: 'ha', name: 'Hausa', nativeName: 'هَوُسَ'},
        {code: 'yo', name: 'Yoruba', nativeName: 'Yorùbá'},
        {code: 'ig', name: 'Igbo', nativeName: 'Asụsụ Igbo'},
        {code: 'ff', name: 'Fula', nativeName: 'Fulfulde'},
        {code: 'wo', name: 'Wolof', nativeName: 'Wollof'},
        {code: 'bm', name: 'Bambara', nativeName: 'bamanankan'},
        {code: 'kr', name: 'Kanuri', nativeName: 'Kanuri'},
        {code: 'dz', name: 'Dzongkha', nativeName: 'རྫོང་ཁ'},
        {code: 'ne', name: 'Nepali', nativeName: 'नेपाली'},
        {code: 'si', name: 'Sinhala', nativeName: 'සිංහල'},
        {code: 'my', name: 'Burmese', nativeName: 'ဗမာစာ'},
        {code: 'km', name: 'Khmer', nativeName: 'ខេមរភាសា'},
        {code: 'lo', name: 'Lao', nativeName: 'ພາສາລາວ'},
        {code: 'th', name: 'Thai', nativeName: 'ไทย'},
        {code: 'bo', name: 'Tibetan', nativeName: 'བོད་ཡིག'},
        {code: 'mn', name: 'Mongolian', nativeName: 'Монгол хэл'},
        {code: 'ug', name: 'Uyghur', nativeName: 'ئۇيغۇرچە‎'},
        {code: 'kk', name: 'Kazakh', nativeName: 'қазақ тілі'},
        {code: 'ky', name: 'Kyrgyz', nativeName: 'Кыргызча'},
        {code: 'uz', name: 'Uzbek', nativeName: 'Ўзбек'},
        {code: 'tk', name: 'Turkmen', nativeName: 'Türkmençe'},
        {code: 'tt', name: 'Tatar', nativeName: 'татар теле'},
        {code: 'ba', name: 'Bashkir', nativeName: 'башҡорт теле'},
        {code: 'cv', name: 'Chuvash', nativeName: 'чӑваш чӗлхи'},
        {code: 'sah', name: 'Yakut', nativeName: 'саха тыла'},
        {code: 'ce', name: 'Chechen', nativeName: 'нохчийн мотт'},
        {code: 'os', name: 'Ossetian', nativeName: 'ирон æвзаг'},
        {code: 'ab', name: 'Abkhaz', nativeName: 'аҧсуа бызшәа'},
        {code: 'ka', name: 'Georgian', nativeName: 'ქართული'},
        {code: 'hy', name: 'Armenian', nativeName: 'Հայերեն'},
        {code: 'az', name: 'Azerbaijani', nativeName: 'azərbaycan dili'},
        {code: 'ku', name: 'Kurdish', nativeName: 'Kurdî'},
        {code: 'ps', name: 'Pashto', nativeName: 'پښتو'},
        {code: 'sd', name: 'Sindhi', nativeName: 'सिन्धी'},
        {code: 'ks', name: 'Kashmiri', nativeName: 'कश्मीरी'},
        {code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्'},
        {code: 'pi', name: 'Pāli', nativeName: 'पाऴि'},
        {code: 'bh', name: 'Bihari', nativeName: 'भोजपुरी'},
        {code: 'as', name: 'Assamese', nativeName: 'অসমীয়া'},
        {code: 'or', name: 'Oriya', nativeName: 'ଓଡ଼ିଆ'},
        {code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം'},
        {code: 'ta', name: 'Tamil', nativeName: 'தமிழ்'},
        {code: 'te', name: 'Telugu', nativeName: 'తెలుగు'},
        {code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ'},
        {code: 'mr', name: 'Marathi', nativeName: 'मराठी'},
        {code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી'},
        {code: 'pa', name: 'Panjabi', nativeName: 'ਪੰਜਾਬੀ'},
        {code: 'bn', name: 'Bengali', nativeName: 'বাংলা'},
        {code: 'ur', name: 'Urdu', nativeName: 'اردو'},
        {code: 'hi', name: 'Hindi', nativeName: 'हिन्दी'},
        {code: 'si', name: 'Sinhala', nativeName: 'සිංහල'},
        {code: 'my', name: 'Burmese', nativeName: 'ဗမာစာ'},
        {code: 'km', name: 'Khmer', nativeName: 'ខេមរភាសា'},
        {code: 'lo', name: 'Lao', nativeName: 'ພາສາລາວ'},
        {code: 'th', name: 'Thai', nativeName: 'ไทย'},
        {code: 'bo', name: 'Tibetan', nativeName: 'བོད་ཡིག'},
        {code: 'mn', name: 'Mongolian', nativeName: 'Монгол хэл'},
        {code: 'ug', name: 'Uyghur', nativeName: 'ئۇيغۇرچە‎'},
        {code: 'kk', name: 'Kazakh', nativeName: 'қазақ тілі'},
        {code: 'ky', name: 'Kyrgyz', nativeName: 'Кыргызча'},
        {code: 'uz', name: 'Uzbek', nativeName: 'Ўзбек'},
        {code: 'tk', name: 'Turkmen', nativeName: 'Türkmençe'},
        {code: 'tt', name: 'Tatar', nativeName: 'татар теле'},
        {code: 'ba', name: 'Bashkir', nativeName: 'башҡорт теле'},
        {code: 'cv', name: 'Chuvash', nativeName: 'чӑваш чӗлхи'},
        {code: 'sah', name: 'Yakut', nativeName: 'саха тыла'},
        {code: 'ce', name: 'Chechen', nativeName: 'нохчийн мотт'},
        {code: 'os', name: 'Ossetian', nativeName: 'ирон æвзаг'},
        {code: 'ab', name: 'Abkhaz', nativeName: 'аҧсуа бызшәа'},
        {code: 'ka', name: 'Georgian', nativeName: 'ქართული'},
        {code: 'hy', name: 'Armenian', nativeName: 'Հայերեն'},
        {code: 'az', name: 'Azerbaijani', nativeName: 'azərbaycan dili'},
        {code: 'ku', name: 'Kurdish', nativeName: 'Kurdî'},
        {code: 'ps', name: 'Pashto', nativeName: 'پښتو'},
        {code: 'sd', name: 'Sindhi', nativeName: 'सिन्धी'},
        {code: 'ks', name: 'Kashmiri', nativeName: 'कश्मीरी'},
        {code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्'},
        {code: 'pi', name: 'Pāli', nativeName: 'पाऴि'},
        {code: 'bh', name: 'Bihari', nativeName: 'भोजपुरी'},
        {code: 'as', name: 'Assamese', nativeName: 'অসমীয়া'},
        {code: 'or', name: 'Oriya', nativeName: 'ଓଡ଼ିଆ'}
    ],
    zh:[
        {code: 'en', name: '英语', nativeName: 'English'},
        {code: 'zh', name: '中文', nativeName: '中文'},
        {code: 'hi', name: '印地语', nativeName: 'हिन्दी'},
        {code: 'es', name: '西班牙语', nativeName: 'Español'},
        {code: 'fr', name: '法语', nativeName: 'Français'},
        {code: 'ar', name: '阿拉伯语', nativeName: 'العربية'},
        {code: 'bn', name: '孟加拉语', nativeName: 'বাংলা'},
        {code: 'ru', name: '俄语', nativeName: 'Русский'},
        {code: 'pt', name: '葡萄牙语', nativeName: 'Português'},
        {code: 'ur', name: '乌尔都语', nativeName: 'اردو'},
        {code: 'id', name: '印度尼西亚语', nativeName: 'Bahasa Indonesia'},
        {code: 'de', name: '德语', nativeName: 'Deutsch'},
        {code: 'ja', name: '日语', nativeName: '日本語'},
        {code: 'sw', name: '斯瓦希里语', nativeName: 'Kiswahili'},
        {code: 'mr', name: '马拉地语', nativeName: 'मराठी'},
        {code: 'te', name: '泰卢固语', nativeName: 'తెలుగు'},
        {code: 'tr', name: '土耳其语', nativeName: 'Türkçe'},
        {code: 'ta', name: '泰米尔语', nativeName: 'தமிழ்'},
        {code: 'vi', name: '越南语', nativeName: 'Tiếng Việt'},
        {code: 'ko', name: '韩语', nativeName: '한국어'},
        {code: 'it', name: '意大利语', nativeName: 'Italiano'},
        {code: 'th', name: '泰语', nativeName: 'ไทย'},
        {code: 'gu', name: '古吉拉特语', nativeName: 'ગુજરાતી'},
        {code: 'pl', name: '波兰语', nativeName: 'Polski'},
        {code: 'uk', name: '乌克兰语', nativeName: 'Українська'},
        {code: 'ml', name: '马拉雅拉姆语', nativeName: 'മലയാളം'},
        {code: 'kn', name: '卡纳达语', nativeName: 'ಕನ್ನಡ'},
        {code: 'or', name: '奥里亚语', nativeName: 'ଓଡ଼ିଆ'},
        {code: 'my', name: '缅甸语', nativeName: 'ဗမာစာ'},
        {code: 'pa', name: '旁遮普语', nativeName: 'ਪੰਜਾਬੀ'},
        {code: 'fa', name: '波斯语', nativeName: 'فارسی'},
        {code: 'nl', name: '荷兰语', nativeName: 'Nederlands'},
        {code: 'fil', name: '菲律宾语', nativeName: 'Wikang Filipino'},
        {code: 'xh', name: '科萨语', nativeName: 'isiXhosa'},
        {code: 'zu', name: '祖鲁语', nativeName: 'isiZulu'},
        {code: 'ro', name: '罗马尼亚语', nativeName: 'Română'},
        {code: 'el', name: '希腊语', nativeName: 'Ελληνικά'},
        {code: 'cs', name: '捷克语', nativeName: 'čeština'},
        {code: 'sv', name: '瑞典语', nativeName: 'Svenska'},
        {code: 'hu', name: '匈牙利语', nativeName: 'magyar'},
        {code: 'fi', name: '芬兰语', nativeName: 'suomi'},
        {code: 'da', name: '丹麦语', nativeName: 'Dansk'},
        {code: 'he', name: '希伯来语', nativeName: 'עברית'},
        {code: 'no', name: '挪威语', nativeName: 'Norsk'},
        {code: 'sk', name: '斯洛伐克语', nativeName: 'slovenčina'},
        {code: 'sl', name: '斯洛文尼亚语', nativeName: 'slovenščina'},
        {code: 'hr', name: '克罗地亚语', nativeName: 'Hrvatski'},
        {code: 'bg', name: '保加利亚语', nativeName: 'български език'},
        {code: 'lt', name: '立陶宛语', nativeName: 'lietuvių kalba'},
        {code: 'lv', name: '拉脱维亚语', nativeName: 'latviešu valoda'},
        {code: 'et', name: '爱沙尼亚语', nativeName: 'eesti'},
        {code: 'ga', name: '爱尔兰语', nativeName: 'Gaeilge'},
        {code: 'mt', name: '马耳他语', nativeName: 'Malti'},
        {code: 'cy', name: '威尔士语', nativeName: 'Cymraeg'},
        {code: 'gd', name: '苏格兰盖尔语', nativeName: 'Gàidhlig'},
        {code: 'is', name: '冰岛语', nativeName: 'Íslenska'},
        {code: 'sq', name: '阿尔巴尼亚语', nativeName: 'Shqip'},
        {code: 'mk', name: '马其顿语', nativeName: 'македонски јазик'},
        {code: 'bs', name: '波斯尼亚语', nativeName: 'bosanski jezik'},
        {code: 'sr', name: '塞尔维亚语', nativeName: 'српски језик'},
        {code: 'ca', name: '加泰罗尼亚语', nativeName: 'Català'},
        {code: 'eu', name: '巴斯克语', nativeName: 'euskara'},
        {code: 'gl', name: '加利西亚语', nativeName: 'galego'},
        {code: 'oc', name: '奥克语', nativeName: 'occitan'},
        {code: 'ast', name: '阿斯图里亚斯语', nativeName: 'Asturianu'},
        {code: 'an', name: '阿拉贡语', nativeName: 'aragonés'},
        {code: 'sc', name: '撒丁语', nativeName: 'sardu'},
        {code: 'rm', name: '罗曼什语', nativeName: 'rumantsch grischun'},
        {code: 'fur', name: '弗留利语', nativeName: 'Furlan'},
        {code: 'lad', name: '拉迪诺语', nativeName: 'Ladino'},
        {code: 'wa', name: '瓦隆语', nativeName: 'walon'},
        {code: 'br', name: '布列塔尼语', nativeName: 'brezhoneg'},
        {code: 'co', name: '科西嘉语', nativeName: 'corsu'},
        {code: 'gv', name: '马恩岛语', nativeName: 'Gaelg'},
        {code: 'kw', name: '康沃尔语', nativeName: 'Kernewek'},
        {code: 'fy', name: '西弗里斯兰语', nativeName: 'Frysk'},
        {code: 'li', name: '林堡语', nativeName: 'Limburgs'},
        {code: 'af', name: '南非荷兰语', nativeName: 'Afrikaans'},
        {code: 'st', name: '南索托语', nativeName: 'Sesotho'},
        {code: 'tn', name: '茨瓦纳语', nativeName: 'Setswana'},
        {code: 'ts', name: '聪加语', nativeName: 'Xitsonga'},
        {code: 'ss', name: '斯威士语', nativeName: 'SiSwati'},
        {code: 've', name: '文达语', nativeName: 'Tshivenḓa'},
        {code: 'nr', name: '南恩德贝莱语', nativeName: 'isiNdebele'},
        {code: 'xh', name: '科萨语', nativeName: 'isiXhosa'},
        {code: 'zu', name: '祖鲁语', nativeName: 'isiZulu'},
        {code: 'sn', name: '绍纳语', nativeName: 'chiShona'},
        {code: 'ny', name: '齐切瓦语', nativeName: 'chiCheŵa'},
        {code: 'mg', name: '马尔加什语', nativeName: 'fiteny malagasy'},
        {code: 'rw', name: '卢旺达语', nativeName: 'Ikinyarwanda'},
        {code: 'rn', name: '隆迪语', nativeName: 'Ikirundi'},
        {code: 'sg', name: '桑戈语', nativeName: 'yângâ tî sängö'},
        {code: 'lg', name: '干达语', nativeName: 'Luganda'},
        {code: 'ln', name: '林加拉语', nativeName: 'Lingála'},
        {code: 'sw', name: '斯瓦希里语', nativeName: 'Kiswahili'},
        {code: 'so', name: '索马里语', nativeName: 'Soomaaliga'},
        {code: 'om', name: '奥罗莫语', nativeName: 'Afaan Oromoo'},
        {code: 'ha', name: '豪萨语', nativeName: 'هَوُسَ'},
        {code: 'yo', name: '约鲁巴语', nativeName: 'Yorùbá'},
        {code: 'ig', name: '伊博语', nativeName: 'Asụsụ Igbo'},
        {code: 'ff', name: '富拉语', nativeName: 'Fulfulde'},
        {code: 'wo', name: '沃洛夫语', nativeName: 'Wollof'},
        {code: 'bm', name: '班巴拉语', nativeName: 'bamanankan'},
        {code: 'kr', name: '卡努里语', nativeName: 'Kanuri'},
        {code: 'dz', name: '宗卡语', nativeName: 'རྫོང་ཁ'},
        {code: 'ne', name: '尼泊尔语', nativeName: 'नेपाली'},
        {code: 'si', name: '僧伽罗语', nativeName: 'සිංහල'},
        {code: 'my', name: '缅甸语', nativeName: 'ဗမာစာ'},
        {code: 'km', name: '高棉语', nativeName: 'ខេមរភាសា'},
        {code: 'lo', name: '老挝语', nativeName: 'ພາສາລາວ'},
        {code: 'th', name: '泰语', nativeName: 'ไทย'},
        {code: 'bo', name: '藏语', nativeName: 'བོད་ཡིག'},
        {code: 'mn', name: '蒙古语', nativeName: 'Монгол хэл'},
        {code: 'ug', name: '维吾尔语', nativeName: 'ئۇيغۇرچە‎'},
        {code: 'kk', name: '哈萨克语', nativeName: 'қазақ тілі'},
        {code: 'ky', name: '吉尔吉斯语', nativeName: 'Кыргызча'},
        {code: 'uz', name: '乌兹别克语', nativeName: 'Ўзбек'},
        {code: 'tk', name: '土库曼语', nativeName: 'Türkmençe'},
        {code: 'tt', name: '鞑靼语', nativeName: 'татар теле'},
        {code: 'ba', name: '巴什基尔语', nativeName: 'башҡорт теле'},
        {code: 'cv', name: '楚瓦什语', nativeName: 'чӑваш чӗлхи'},
        {code: 'sah', name: '雅库特语', nativeName: 'саха тыла'},
        {code: 'ce', name: '车臣语', nativeName: 'нохчийн мотт'},
        {code: 'os', name: '奥塞梯语', nativeName: 'ирон æвзаг'},
        {code: 'ab', name: '阿布哈兹语', nativeName: 'аҧсуа бызшәа'},
        {code: 'ka', name: '格鲁吉亚语', nativeName: 'ქართული'},
        {code: 'hy', name: '亚美尼亚语', nativeName: 'Հայերեն'},
        {code: 'az', name: '阿塞拜疆语', nativeName: 'azərbaycan dili'},
        {code: 'ku', name: '库尔德语', nativeName: 'Kurdî'},
        {code: 'ps', name: '普什图语', nativeName: 'پښتو'},
        {code: 'sd', name: '信德语', nativeName: 'सिन्धी'},
        {code: 'ks', name: '克什米尔语', nativeName: 'कश्मीरी'},
        {code: 'sa', name: '梵语', nativeName: 'संस्कृतम्'},
        {code: 'pi', name: '巴利语', nativeName: 'पाऴि'},
        {code: 'bh', name: '比哈尔语', nativeName: 'भोजपुरी'},
        {code: 'as', name: '阿萨姆语', nativeName: 'অসমীয়া'},
        {code: 'or', name: '奥里亚语', nativeName: 'ଓଡ଼ିଆ'},
        {code: 'ml', name: '马拉雅拉姆语', nativeName: 'മലയാളം'},
        {code: 'ta', name: '泰米尔语', nativeName: 'தமிழ்'},
        {code: 'te', name: '泰卢固语', nativeName: 'తెలుగు'},
        {code: 'kn', name: '卡纳达语', nativeName: 'ಕನ್ನಡ'},
        {code: 'mr', name: '马拉地语', nativeName: 'मराठी'},
        {code: 'gu', name: '古吉拉特语', nativeName: 'ગુજરાતી'},
        {code: 'pa', name: '旁遮普语', nativeName: 'ਪੰਜਾਬੀ'},
        {code: 'bn', name: '孟加拉语', nativeName: 'বাংলা'},
        {code: 'ur', name: '乌尔都语', nativeName: 'اردو'},
        {code: 'hi', name: '印地语', nativeName: 'हिन्दी'},
        {code: 'si', name: '僧伽罗语', nativeName: 'සිංහල'},
        {code: 'my', name: '缅甸语', nativeName: 'ဗမာစာ'},
        {code: 'km', name: '高棉语', nativeName: 'ខេមរភាសា'},
        {code: 'lo', name: '老挝语', nativeName: 'ພາສາລາວ'},
        {code: 'th', name: '泰语', nativeName: 'ไทย'},
        {code: 'bo', name: '藏语', nativeName: 'བོད་ཡིག'},
        {code: 'mn', name: '蒙古语', nativeName: 'Монгол хэл'},
        {code: 'ug', name: '维吾尔语', nativeName: 'ئۇيغۇرچە‎'},
        {code: 'kk', name: '哈萨克语', nativeName: 'қазақ тілі'},
        {code: 'ky', name: '吉尔吉斯语', nativeName: 'Кыргызча'},
        {code: 'uz', name: '乌兹别克语', nativeName: 'Ўзбек'},
        {code: 'tk', name: '土库曼语', nativeName: 'Türkmençe'},
        {code: 'tt', name: '鞑靼语', nativeName: 'татар теле'},
        {code: 'ba', name: '巴什基尔语', nativeName: 'башҡорт теле'},
        {code: 'cv', name: '楚瓦什语', nativeName: 'чӑваш чӗлхи'},
        {code: 'sah', name: '雅库特语', nativeName: 'саха тыла'},
        {code: 'ce', name: '车臣语', nativeName: 'нохчийн мотт'},
        {code: 'os', name: '奥塞梯语', nativeName: 'ирон æвзаг'},
        {code: 'ab', name: '阿布哈兹语', nativeName: 'аҧсуа бызшәа'},
        {code: 'ka', name: '格鲁吉亚语', nativeName: 'ქართული'},
        {code: 'hy', name: '亚美尼亚语', nativeName: 'Հայերեն'},
        {code: 'az', name: '阿塞拜疆语', nativeName: 'azərbaycan dili'},
        {code: 'ku', name: '库尔德语', nativeName: 'Kurdî'},
        {code: 'ps', name: '普什图语', nativeName: 'پښتو'},
        {code: 'en', name: 'English', nativeName: 'English'},
        {code: 'zh', name: 'Chinese', nativeName: '中文'},
        {code: 'hi', name: 'Hindi', nativeName: 'हिन्दी'},
        {code: 'es', name: 'Spanish', nativeName: 'Español'},
        {code: 'fr', name: 'French', nativeName: 'Français'},
        {code: 'ar', name: 'Arabic', nativeName: 'العربية'},
        {code: 'bn', name: 'Bengali', nativeName: 'বাংলা'},
        {code: 'ru', name: 'Russian', nativeName: 'Русский'},
        {code: 'pt', name: 'Portuguese', nativeName: 'Português'},
        {code: 'ur', name: 'Urdu', nativeName: 'اردو'},
        {code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia'},
        {code: 'de', name: 'German', nativeName: 'Deutsch'},
        {code: 'ja', name: 'Japanese', nativeName: '日本語'},
        {code: 'sw', name: 'Swahili', nativeName: 'Kiswahili'},
        {code: 'mr', name: 'Marathi', nativeName: 'मराठी'},
        {code: 'te', name: 'Telugu', nativeName: 'తెలుగు'},
        {code: 'tr', name: 'Turkish', nativeName: 'Türkçe'},
        {code: 'ta', name: 'Tamil', nativeName: 'தமிழ்'},
        {code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt'},
        {code: 'ko', name: 'Korean', nativeName: '한국어'},
        {code: 'it', name: 'Italian', nativeName: 'Italiano'},
        {code: 'th', name: 'Thai', nativeName: 'ไทย'},
        {code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી'},
        {code: 'pl', name: 'Polish', nativeName: 'Polski'},
        {code: 'uk', name: 'Ukrainian', nativeName: 'Українська'},
        {code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം'},
        {code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ'},
        {code: 'or', name: 'Oriya', nativeName: 'ଓଡ଼ିଆ'},
        {code: 'my', name: 'Burmese', nativeName: 'ဗမာစာ'},
        {code: 'pa', name: 'Panjabi', nativeName: 'ਪੰਜਾਬੀ'},
        {code: 'fa', name: 'Persian', nativeName: 'فارسی'},
        {code: 'nl', name: 'Dutch', nativeName: 'Nederlands'},
        {code: 'fil', name: 'Filipino', nativeName: 'Wikang Filipino'},
        {code: 'xh', name: 'Xhosa', nativeName: 'isiXhosa'},
        {code: 'zu', name: 'Zulu', nativeName: 'isiZulu'},
        {code: 'ro', name: 'Romanian', nativeName: 'Română'},
        {code: 'el', name: 'Greek', nativeName: 'Ελληνικά'},
        {code: 'cs', name: 'Czech', nativeName: 'čeština'},
        {code: 'sv', name: 'Swedish', nativeName: 'Svenska'},
        {code: 'hu', name: 'Hungarian', nativeName: 'magyar'},
        {code: 'fi', name: 'Finnish', nativeName: 'suomi'},
        {code: 'da', name: 'Danish', nativeName: 'Dansk'},
        {code: 'he', name: 'Hebrew', nativeName: 'עברית'},
        {code: 'no', name: 'Norwegian', nativeName: 'Norsk'},
        {code: 'sk', name: 'Slovak', nativeName: 'slovenčina'},
        {code: 'sl', name: 'Slovenian', nativeName: 'slovenščina'},
        {code: 'hr', name: 'Croatian', nativeName: 'Hrvatski'},
        {code: 'bg', name: 'Bulgarian', nativeName: 'български език'},
        {code: 'lt', name: 'Lithuanian', nativeName: 'lietuvių kalba'},
        {code: 'lv', name: 'Latvian', nativeName: 'latviešu valoda'},
        {code: 'et', name: 'Estonian', nativeName: 'eesti'},
        {code: 'ga', name: 'Irish', nativeName: 'Gaeilge'},
        {code: 'mt', name: 'Maltese', nativeName: 'Malti'},
        {code: 'cy', name: 'Welsh', nativeName: 'Cymraeg'},
        {code: 'gd', name: 'Scottish Gaelic', nativeName: 'Gàidhlig'},
        {code: 'is', name: 'Icelandic', nativeName: 'Íslenska'},
        {code: 'sq', name: 'Albanian', nativeName: 'Shqip'},
        {code: 'mk', name: 'Macedonian', nativeName: 'македонски јазик'},
        {code: 'bs', name: 'Bosnian', nativeName: 'bosanski jezik'},
        {code: 'sr', name: 'Serbian', nativeName: 'српски језик'},
        {code: 'ca', name: 'Catalan', nativeName: 'Català'},
        {code: 'eu', name: 'Basque', nativeName: 'euskara'},
        {code: 'gl', name: 'Galician', nativeName: 'galego'},
        {code: 'oc', name: 'Occitan', nativeName: 'occitan'},
        {code: 'ast', name: 'Asturian', nativeName: 'Asturianu'},
        {code: 'an', name: 'Aragonese', nativeName: 'aragonés'},
        {code: 'sc', name: 'Sardinian', nativeName: 'sardu'},
        {code: 'rm', name: 'Romansh', nativeName: 'rumantsch grischun'},
        {code: 'fur', name: 'Friulian', nativeName: 'Furlan'},
        {code: 'lad', name: 'Ladino', nativeName: 'Ladino'},
        {code: 'wa', name: 'Walloon', nativeName: 'walon'},
        {code: 'br', name: 'Breton', nativeName: 'brezhoneg'},
        {code: 'co', name: 'Corsican', nativeName: 'corsu'},
        {code: 'gv', name: 'Manx', nativeName: 'Gaelg'},
        {code: 'kw', name: 'Cornish', nativeName: 'Kernewek'},
        {code: 'fy', name: 'Western Frisian', nativeName: 'Frysk'},
        {code: 'li', name: 'Limburgish', nativeName: 'Limburgs'},
        {code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans'},
        {code: 'st', name: 'Southern Sotho', nativeName: 'Sesotho'},
        {code: 'tn', name: 'Tswana', nativeName: 'Setswana'},
        {code: 'ts', name: 'Tsonga', nativeName: 'Xitsonga'},
        {code: 'ss', name: 'Swati', nativeName: 'SiSwati'},
        {code: 've', name: 'Venda', nativeName: 'Tshivenḓa'},
        {code: 'nr', name: 'Southern Ndebele', nativeName: 'isiNdebele'},
        {code: 'xh', name: 'Xhosa', nativeName: 'isiXhosa'},
        {code: 'zu', name: 'Zulu', nativeName: 'isiZulu'},
        {code: 'sn', name: 'Shona', nativeName: 'chiShona'},
        {code: 'ny', name: 'Chichewa', nativeName: 'chiCheŵa'},
        {code: 'mg', name: 'Malagasy', nativeName: 'fiteny malagasy'},
        {code: 'rw', name: 'Kinyarwanda', nativeName: 'Ikinyarwanda'},
        {code: 'rn', name: 'Kirundi', nativeName: 'Ikirundi'},
        {code: 'sg', name: 'Sango', nativeName: 'yângâ tî sängö'},
        {code: 'lg', name: 'Ganda', nativeName: 'Luganda'},
        {code: 'ln', name: 'Lingala', nativeName: 'Lingála'},
        {code: 'sw', name: 'Swahili', nativeName: 'Kiswahili'},
        {code: 'so', name: 'Somali', nativeName: 'Soomaaliga'},
        {code: 'om', name: 'Oromo', nativeName: 'Afaan Oromoo'},
        {code: 'ha', name: 'Hausa', nativeName: 'هَوُسَ'},
        {code: 'yo', name: 'Yoruba', nativeName: 'Yorùbá'},
        {code: 'ig', name: 'Igbo', nativeName: 'Asụsụ Igbo'},
        {code: 'ff', name: 'Fula', nativeName: 'Fulfulde'},
        {code: 'wo', name: 'Wolof', nativeName: 'Wollof'},
        {code: 'bm', name: 'Bambara', nativeName: 'bamanankan'},
        {code: 'kr', name: 'Kanuri', nativeName: 'Kanuri'},
        {code: 'dz', name: 'Dzongkha', nativeName: 'རྫོང་ཁ'},
        {code: 'ne', name: 'Nepali', nativeName: 'नेपाली'},
        {code: 'si', name: 'Sinhala', nativeName: 'සිංහල'},
        {code: 'my', name: 'Burmese', nativeName: 'ဗမာစာ'},
        {code: 'km', name: 'Khmer', nativeName: 'ខេមរភាសា'},
        {code: 'lo', name: 'Lao', nativeName: 'ພາສາລາວ'},
        {code: 'th', name: 'Thai', nativeName: 'ไทย'},
        {code: 'bo', name: 'Tibetan', nativeName: 'བོད་ཡིག'},
        {code: 'mn', name: 'Mongolian', nativeName: 'Монгол хэл'},
        {code: 'ug', name: 'Uyghur', nativeName: 'ئۇيغۇرچە‎'},
        {code: 'kk', name: 'Kazakh', nativeName: 'қазақ тілі'},
        {code: 'ky', name: 'Kyrgyz', nativeName: 'Кыргызча'},
        {code: 'uz', name: 'Uzbek', nativeName: 'Ўзбек'},
        {code: 'tk', name: 'Turkmen', nativeName: 'Türkmençe'},
        {code: 'tt', name: 'Tatar', nativeName: 'татар теле'},
        {code: 'ba', name: 'Bashkir', nativeName: 'башҡорт теле'},
        {code: 'cv', name: 'Chuvash', nativeName: 'чӑваш чӗлхи'},
        {code: 'sah', name: 'Yakut', nativeName: 'саха тыла'},
        {code: 'ce', name: 'Chechen', nativeName: 'нохчийн мотт'},
        {code: 'os', name: 'Ossetian', nativeName: 'ирон æвзаг'},
        {code: 'ab', name: 'Abkhaz', nativeName: 'аҧсуа бызшәа'},
        {code: 'ka', name: 'Georgian', nativeName: 'ქართული'},
        {code: 'hy', name: 'Armenian', nativeName: 'Հայերեն'},
        {code: 'az', name: 'Azerbaijani', nativeName: 'azərbaycan dili'},
        {code: 'ku', name: 'Kurdish', nativeName: 'Kurdî'},
        {code: 'ps', name: 'Pashto', nativeName: 'پښتو'},
        {code: 'sd', name: 'Sindhi', nativeName: 'सिन्धी'},
        {code: 'ks', name: 'Kashmiri', nativeName: 'कश्मीरी'},
        {code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्'},
        {code: 'pi', name: 'Pāli', nativeName: 'पाऴि'},
        {code: 'bh', name: 'Bihari', nativeName: 'भोजपुरी'},
        {code: 'as', name: 'Assamese', nativeName: 'অসমীয়া'},
        {code: 'or', name: 'Oriya', nativeName: 'ଓଡ଼ିଆ'},
        {code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം'},
        {code: 'ta', name: 'Tamil', nativeName: 'தமிழ்'},
        {code: 'te', name: 'Telugu', nativeName: 'తెలుగు'},
        {code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ'},
        {code: 'mr', name: 'Marathi', nativeName: 'मराठी'},
        {code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી'},
        {code: 'pa', name: 'Panjabi', nativeName: 'ਪੰਜਾਬੀ'},
        {code: 'bn', name: 'Bengali', nativeName: 'বাংলা'},
        {code: 'ur', name: 'Urdu', nativeName: 'اردو'},
        {code: 'hi', name: 'Hindi', nativeName: 'हिन्दी'},
        {code: 'si', name: 'Sinhala', nativeName: 'සිංහල'},
        {code: 'my', name: 'Burmese', nativeName: 'ဗမာစာ'},
        {code: 'km', name: 'Khmer', nativeName: 'ខេមរភាសា'},
        {code: 'lo', name: 'Lao', nativeName: 'ພາສາລາວ'},
        {code: 'th', name: 'Thai', nativeName: 'ไทย'},
        {code: 'bo', name: 'Tibetan', nativeName: 'བོད་ཡིག'},
        {code: 'mn', name: 'Mongolian', nativeName: 'Монгол хэл'},
        {code: 'ug', name: 'Uyghur', nativeName: 'ئۇيغۇرچە‎'},
        {code: 'kk', name: 'Kazakh', nativeName: 'қазақ тілі'},
        {code: 'ky', name: 'Kyrgyz', nativeName: 'Кыргызча'},
        {code: 'uz', name: 'Uzbek', nativeName: 'Ўзбек'},
        {code: 'tk', name: 'Turkmen', nativeName: 'Türkmençe'},
        {code: 'tt', name: 'Tatar', nativeName: 'татар теле'},
        {code: 'ba', name: 'Bashkir', nativeName: 'башҡорт теле'},
        {code: 'cv', name: 'Chuvash', nativeName: 'чӑваш чӗлхи'},
        {code: 'sah', name: 'Yakut', nativeName: 'саха тыла'},
        {code: 'ce', name: 'Chechen', nativeName: 'нохчийн мотт'},
        {code: 'os', name: 'Ossetian', nativeName: 'ирон æвзаг'},
        {code: 'ab', name: 'Abkhaz', nativeName: 'аҧсуа бызшәа'},
        {code: 'ka', name: 'Georgian', nativeName: 'ქართული'},
        {code: 'hy', name: 'Armenian', nativeName: 'Հայերեն'},
        {code: 'az', name: 'Azerbaijani', nativeName: 'azərbaycan dili'},
        {code: 'ku', name: 'Kurdish', nativeName: 'Kurdî'},
        {code: 'ps', name: 'Pashto', nativeName: 'پښتو'},
        {code: 'sd', name: 'Sindhi', nativeName: 'सिन्धी'},
        {code: 'ks', name: 'Kashmiri', nativeName: 'कश्मीरी'},
        {code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्'},
        {code: 'pi', name: 'Pāli', nativeName: 'पाऴि'},
        {code: 'bh', name: 'Bihari', nativeName: 'भोजपुरी'},
        {code: 'as', name: 'Assamese', nativeName: 'অসমীয়া'},
        {code: 'or', name: 'Oriya', nativeName: 'ଓଡ଼ିଆ'}
    ]
} 